language: node_js
node_js:
  - "20"

dist: jammy  # Ubuntu 22.04 (modern, supports Node 20)

services:
  - mongodb
  - redis-server

env:
  global:
    - NODE_ENV=ci
    - PORT=3000

cache:
  npm: true
  directories:
    - client/node_modules

install:
  - npm ci
  - npm run build

script:
  - npm run start &
  - sleep 5
  - npm test

branches:
  only:
    - main
